### ISSUE TITLE
No contextual menu appears for divtranslate

### ISSUE THREAD

**Issue by marc0s** [AdrianArroyoCalle/firefox-addons#50]
Hi,

I've just installed divtranslate 1.0 and I expected to have added some contextual menu for translating selected text, but there's nothing on my menues.

I'm using Iceweasel 31.1.0 on Debian Jessie. Please tell me if you need anything else to help debugging.

Thanks.

**Comment by AdrianArroyoCalle** [comment]
Fixed on 1.1.0 which now uses the API from APY (Apertium in Python)
